server:
  port: ${PORT:9000}

spring:
  datasource:
    url: jdbc:h2:mem:graphql101
    username: sa
    password:
    driverClassName: org.h2.Driver

  sql:
    init.mode: always

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      # We will handle table creation in a schema file
      ddl-auto: none


  h2:
    # Open http://localhost:9000/h2-console in a browser to manage the in-memory database.  Use the url, username
    # and password defined above to log in.
    console.enabled: true
